export const servicios = [
  {
    slug: 'bienes-raices',
    proceso: ['Identificación del activo', 'Debida diligencia jurídica y técnica', 'Estructuración de la operación', 'Incorporación y administración'],
    faqs: [
      { p: '¿Qué tipo de activos incorpora la división?', r: 'Inmuebles urbanos, industriales y rurales, además de bienes muebles asociados a la operación. Cada incorporación se evalúa por situación jurídica, factibilidad técnica y proyección de renta.' },
      { p: '¿MAPI GLOBAL opera como intermediario o como titular?', r: 'Opera en ambos roles. Puede adquirir el activo para el portafolio del holding o estructurar la operación entre terceros bajo mandato.' },
      { p: '¿En qué jurisdicciones trabaja la división?', r: 'La estructura está preparada para operar en distintos marcos regulatorios, con verificación registral y tributaria previa a cada transacción.' },
      { p: '¿Cuál es el horizonte de inversión?', r: 'Largo plazo. El criterio es la permanencia y puesta en valor del activo, no la rotación de corto plazo.' },
    ],
    imagen: '/img/bienes-raices.webp',
    titulo: 'Bienes Raíces',
    resumen: 'Compra, venta y desarrollo de bienes inmuebles y muebles.',
    descripcion: [
      'La división de bienes raíces de MAPI GLOBAL administra la adquisición, enajenación y desarrollo de activos inmuebles y muebles. Su mandato es la conformación de un patrimonio estable, con horizonte de largo plazo y criterios de valuación conservadores.',
      'Las operaciones se estructuran sobre análisis de suelo, situación jurídica, factibilidad técnica y proyección de renta. Cada activo se incorpora al portafolio únicamente cuando cumple los umbrales de riesgo definidos por el holding.',
      'La división opera de forma coordinada con construcción y logística, lo que permite integrar la cadena completa: adquisición del terreno, desarrollo de la obra y habilitación operativa del inmueble.',
    ],
    capacidades: [
      { titulo: 'Adquisición de activos', texto: 'Identificación, valuación y compra de inmuebles urbanos, industriales y rurales.' },
      { titulo: 'Enajenación y colocación', texto: 'Estructuración de operaciones de venta y transferencia de bienes muebles e inmuebles.' },
      { titulo: 'Desarrollo patrimonial', texto: 'Puesta en valor de activos subutilizados mediante intervención técnica y regularización.' },
      { titulo: 'Administración de portafolio', texto: 'Control documental, seguimiento de rentabilidad y reporte periódico al holding.' },
    ],
  },
  {
    slug: 'refinacion',
    proceso: ['Recepción y trazabilidad del material', 'Tratamiento industrial', 'Verificación analítica por lote', 'Entrega y despacho'],
    faqs: [
      { p: '¿Qué materiales procesa la división?', r: 'Materiales industriales en general, conforme a la especificación técnica acordada con el cliente y a la normativa aplicable en cada jurisdicción.' },
      { p: '¿Cómo se controla la calidad del producto?', r: 'Con verificación analítica por lote y emisión de certificado de resultados. Ningún lote se libera sin registro documental completo.' },
      { p: '¿Se exige trazabilidad de origen?', r: 'Sí. La documentación de procedencia y cadena de custodia es condición de aceptación para todo material que ingresa a las instalaciones.' },
      { p: '¿La división se encarga del transporte?', r: 'Sí. La operación se coordina con la división de logística para el tránsito entre planta, puerto y destino final.' },
    ],
    imagen: '/img/refinacion.webp',
    titulo: 'Refinación',
    resumen: 'Procesamiento y refinado de materiales en general.',
    descripcion: [
      'La división de refinación concentra las operaciones de procesamiento y refinado de materiales. Su alcance abarca la recepción de materia prima, el tratamiento industrial y la entrega de producto conforme a especificación técnica acordada.',
      'La operación se rige por trazabilidad documental completa: origen, lote, proceso aplicado y resultado analítico. Este registro es condición de aceptación para todo material que ingresa a las instalaciones del holding.',
      'La capacidad de refinación se articula con la red logística propia, lo que reduce tiempos de tránsito entre planta, puerto y destino final.',
    ],
    capacidades: [
      { titulo: 'Procesamiento industrial', texto: 'Tratamiento de materiales conforme a especificación técnica y normativa aplicable.' },
      { titulo: 'Control de calidad', texto: 'Verificación analítica por lote, con registro y certificación de resultados.' },
      { titulo: 'Trazabilidad de origen', texto: 'Documentación completa de procedencia y cadena de custodia del material.' },
      { titulo: 'Integración logística', texto: 'Coordinación directa con transporte terrestre, marítimo y despacho aduanero.' },
    ],
  },
  {
    slug: 'logistica',
    proceso: ['Planificación de ruta y modalidad', 'Preparación documental y aduanera', 'Ejecución del tránsito', 'Entrega y reporte de cierre'],
    faqs: [
      { p: '¿Qué modalidades de transporte cubre?', r: 'Aérea, terrestre, fluvial, férrea y marítima, con posibilidad de combinarlas en un solo itinerario multimodal.' },
      { p: '¿Incluye gestión aduanera?', r: 'Sí. La preparación documental, la clasificación arancelaria y el despacho de importación y exportación forman parte del servicio.' },
      { p: '¿Manejan carga sobredimensionada?', r: 'Sí. La carga de proyecto se ejecuta con estudio de ruta previo, análisis de restricciones y coordinación de permisos.' },
      { p: '¿Cómo se informa el estado del embarque?', r: 'Con reporte de estado en cada punto de control de la ruta, desde el origen hasta la entrega en destino.' },
    ],
    imagen: '/img/logistica.webp',
    posicion: '50% 65%',
    titulo: 'Logística',
    resumen: 'Transporte aéreo, terrestre, fluvial, férreo, marítimo y gestión aduanera.',
    triada: true,
    descripcion: [
      'La división de logística ejecuta el movimiento de carga en todas sus modalidades: aérea, terrestre, fluvial, férrea y marítima, con gestión aduanera integrada en cada tramo.',
      'El isotipo de MAPI GLOBAL no es únicamente un signo de crecimiento financiero: es un mapa literal de las rutas de transportación del holding. Las tres líneas ascendentes corresponden a las tres vías sobre las que se sostiene la operación.',
      'Cada embarque se planifica sobre criterios de costo, plazo y exposición al riesgo. La documentación aduanera se prepara con anticipación al arribo, de modo que el despacho no constituya un punto de detención en la cadena.',
    ],
    capacidades: [
      { titulo: 'Transporte multimodal', texto: 'Combinación de vías aérea, terrestre, fluvial, férrea y marítima en un solo itinerario.' },
      { titulo: 'Gestión aduanera', texto: 'Preparación documental, clasificación arancelaria y despacho de importación y exportación.' },
      { titulo: 'Carga de proyecto', texto: 'Movimiento de volumen sobredimensionado e indivisible con estudio de ruta previo.' },
      { titulo: 'Control de tránsito', texto: 'Seguimiento de embarque y reporte de estado en cada punto de control de la ruta.' },
    ],
  },
  {
    slug: 'aeronaves',
    proceso: ['Definición de requerimiento', 'Verificación técnica y registral', 'Cierre de la transacción', 'Traslado y entrega en destino'],
    faqs: [
      { p: '¿Qué tipo de aeronaves comercializa la división?', r: 'Equipos de ala fija y ala rotativa en segmento ejecutivo, comercial y de carga.' },
      { p: '¿Qué verificación técnica se realiza antes de una compra?', r: 'Revisión de bitácoras, ciclos, historial de mantenimiento y condición de aeronavegabilidad, además del análisis registral del equipo.' },
      { p: '¿Acompañan la operación después de la transferencia?', r: 'Sí. La división coordina matriculación, traslado, permisos de sobrevuelo y recepción en destino.' },
      { p: '¿Se puede incorporar la aeronave a la operación del holding?', r: 'Sí. Cuando el equipo se destina a transporte, se integra a la operación de la división de logística.' },
    ],
    imagen: '/img/aeronaves.webp',
    titulo: 'Aeronaves',
    resumen: 'Compra y venta de todo tipo de aeronaves.',
    descripcion: [
      'La división de aeronaves opera la compra y venta de equipos de ala fija y ala rotativa, en segmentos ejecutivo, comercial y de carga. Su función es intermediar y ejecutar transacciones sobre activos aeronáuticos con verificación técnica y jurídica completa.',
      'Cada operación incluye revisión de bitácoras, estado de mantenimiento, situación registral y condición de aeronavegabilidad. La transferencia se formaliza únicamente cuando el expediente técnico está cerrado.',
      'La división acompaña la operación posterior a la compra: matriculación, traslado, y coordinación con la división logística cuando el equipo se incorpora a la flota de transporte del holding.',
    ],
    capacidades: [
      { titulo: 'Intermediación de activos', texto: 'Compra y venta de aeronaves ejecutivas, comerciales y de carga.' },
      { titulo: 'Verificación técnica', texto: 'Revisión de bitácoras, ciclos, mantenimiento y condición de aeronavegabilidad.' },
      { titulo: 'Situación registral', texto: 'Análisis de titularidad, gravámenes y matrícula en jurisdicción de origen y destino.' },
      { titulo: 'Traslado y entrega', texto: 'Coordinación de ferry flight, permisos de sobrevuelo y recepción en destino.' },
    ],
  },
  {
    slug: 'construccion',
    proceso: ['Factibilidad y proyecto', 'Presupuesto y cronograma', 'Ejecución y control de avance', 'Entrega operativa'],
    faqs: [
      { p: '¿Qué tipo de obra ejecuta la división?', r: 'Obra civil residencial, corporativa e industrial, infraestructura de soporte y desarrollos inmobiliarios completos.' },
      { p: '¿Cómo se controla el avance del proyecto?', r: 'Con medición por partida, control presupuestario y reporte periódico. La desviación se informa en el período en que se produce.' },
      { p: '¿Trabajan con presupuesto cerrado?', r: 'Sí. La planificación se sostiene sobre presupuesto cerrado y cronograma verificable acordados antes del inicio de obra.' },
      { p: '¿De dónde proviene el suministro de materiales?', r: 'La integración con las divisiones de bienes raíces y refinación permite controlar tramos críticos del suministro y reducir dependencia de terceros.' },
    ],
    imagen: '/img/construccion.webp',
    titulo: 'Construcción',
    resumen: 'Construcción y desarrollos inmobiliarios.',
    descripcion: [
      'La división de construcción ejecuta obra civil y desarrollos inmobiliarios, desde la etapa de proyecto hasta la entrega operativa. Su alcance cubre edificación, infraestructura y obra industrial.',
      'La planificación se sostiene sobre presupuesto cerrado, cronograma verificable y control de avance por partida. La desviación se reporta al holding en el período en que se produce, no al cierre del proyecto.',
      'La integración con las divisiones de bienes raíces y refinación permite controlar el suministro de materiales y reducir la dependencia de terceros en los tramos críticos de la obra.',
    ],
    capacidades: [
      { titulo: 'Obra civil', texto: 'Edificación residencial, corporativa e industrial bajo especificación de proyecto.' },
      { titulo: 'Desarrollos inmobiliarios', texto: 'Conducción integral del desarrollo, desde factibilidad hasta entrega.' },
      { titulo: 'Infraestructura', texto: 'Ejecución de obra de soporte, urbanización y habilitación de sitio.' },
      { titulo: 'Control de avance', texto: 'Medición por partida, control presupuestario y reporte periódico de desviaciones.' },
    ],
  },
];

export const getServicio = (slug) => servicios.find((s) => s.slug === slug);
